#!/usr/bin/perl -w
# install packages
# install ubuntu packages from a list
# Licence: General Public Licence (GPL Version 3) 
# Maintainer: jeffbeck-at-web-de

use strict;
use Getopt::Long;
use English;

my $help=0;
my $info=0;
my $setup_hubflow=0;
my $owners=0;
my $pull=0;

my @official_branches=("lenny","precise","quantal");

if (not defined $ARGV[0]){
    $ARGV[0]="help";
} 

# lms help
if ($ARGV[0] eq "help"){
       print('
Commands

  lms help
    show this help

  lms update
    update all official branches

');
   print "\n";
       exit;
}



# lms help
if ($ARGV[0] eq "update"){
    my $result=`git branch | grep '*'`;
    chomp($result);
    $result=~s/\*//;
    $result=~s/ //;
    my $old_branch=$result;
    print "Old Branch: $old_branch\n";
    foreach my $branch (@official_branches){
        print "***** Branch $branch *****\n";
        # gibts repo schon
        if ($branch eq $old_branch){
            next;
        } 
        # gibts repo remote?
        my $remote_exists=system("git branch -r | grep $branch");
        if ($remote_exists==0){
            # continue
        } else {
            # nothing to check-out
            next;
        }
        my $exists=system("git branch | grep $branch");;
        print "$branch $exists\n";
        if ($exists==0){
            system("git checkout $branch");
        } else {
            system("git checkout --track -b $branch origin/$branch");
            system("git pull --all");
        }
    }
    system("git checkout $old_branch");
}

